FROM node:10

# Create app directory
RUN mkdir -p /srv/app/wemi2_front_end
WORKDIR /srv/app/wemi2_front_end

# Install app dependencies
# COPY package-lock.json /srv/app/wemi2_front_end/package-lock.json
#COPY package.json /srv/app/wemi2_front_end/package.json
#RUN npm install
# If you are building your code for production
#RUN npm install --only=production

# Bundle app source
COPY . /srv/app/wemi2_front_end

#build
RUN npm run-script build

EXPOSE 3000
CMD [ "npm", "start" ]

