export default {
    parametro_generale: "parametro_generale",
    allegato_offerta_lav: 'allegato_offerta_lav',
    attributo: 'attributo',
    beneficiario_ric_serv_tcb: 'beneficiario_ric_serv_tcb',
    carrello: 'carrello',
    contributo_tcb: 'contributo_tcb',
    contenuto: 'contenuto',
    contenuto_associato: 'contenuto_associato',
    contenuto_stt: 'contenuto_stt',
    conversazione_utente_ente: 'conversazione_utente_ente',
    datiPropriEnte: 'dati_propri_ente',
    destinatario: 'destinatario',
    dominio: 'dominio',
    dominio_tcb: 'dominio_tcb',
    d_categoria_contrattuale_tcb:'d_categoria_contrattuale_tcb',
    d_fascia_oraria: 'd_fascia_oraria',
    d_modalita_erogazione: 'd_modalita_erogazione',
    d_municipio: 'd_municipio',
    d_tipo_offerta: 'd_tipo_offerta',
    d_tipo_servizio: 'd_tipo_servizio',
    d_tipo_dominio_tcb:'d_tipo_dominio_tcb',
    d_tipologia_orario_conv_tcb:'d_tipologia_orario_conv_tcb',
    d_unita_prezzo_servizio: 'd_unita_prezzo_servizio',
    ente: 'ente',
    ente_stt: 'ente_stt',
    errore:'errore',
    indennita_tcb: 'indennita_tcb',
    log_uso_dati_utente:'log_uso_dati_utente',
    mansione: 'mansione',
    media: 'media',
    merchant: 'merchant',
    merchant_log:'merchant_log',
    municipio: 'municipio',
    modalita_pagamento: 'modalita_pagamento',
    pagamento: "pagamento",
    pagamento_stt: "pagamento_stt",
    r_fascia_oraria_erog_srv_ente: 'r_fascia_oraria_erog_srv_ente',
    r_mansione_serv_erog_ente: 'r_mansione_serv_erog_ente',
    r_dest_liv1_servizio_erog: 'r_dest_liv1_servizio_erog',
    r_dest_liv2_servizio_erog: 'r_dest_liv2_servizio_erog',
    r_municipio_servito_serv_ente: 'r_municipio_servito_serv_ente',
    r_municipio_ente_accreditato: 'r_municipio_ente_accreditato',
    r_servzio_accreditato_ente: 'r_servzio_accreditato_ente',
    r_sost_econ_serv_erog_ente: 'r_sost_econ_serv_erog_ente',
    r_operatore_ente: 'r_operatore_ente',
    r_match_ric_lav: 'r_match_ric_lav',
    r_qual_pers_serv_erog_ente:'r_qual_pers_serv_erog_ente',
    r_sede_ente_servizio_erog:'r_sede_ente_servizio_erog',
    recensione_ente: 'recensione_servizio_ente',
    recensione_ente_stt: 'recensione_servizio_ente_stt',
    richiesta_servizio_base: 'richiesta_servizio_base',
    richiesta_servizio_ente: 'richiesta_servizio_ente',
    richiesta_servizio_base_stt: 'richiesta_servizio_base_stt',
    richiesta_servizio_ente_stt: 'richiesta_servizio_ente_stt',
    richiesta_servizio_tcb: 'richiesta_servizio_tcb',
    conversazione_utente: 'conversazione_utente',
    sede_ente: 'sede_ente',
    servizio: 'servizio',
    servizio_tag:'servizio_tag',
    servizio_erogato_ente: 'servizio_erogato_ente',
    servizio_erogato_ente_stt: 'servizio_erogato_ente_stt',
    srv_prezzo:'srv_prezzo',
    srv_prezzo_persone:'srv_prezzo_persone',
    srv_prezzo_persone_quantita:'srv_prezzo_persone_quantita',
    tipologia_contenuto: 'tipologia_contenuto',
    transazione_voucher: 'transazione_voucher',
    utente: 'utente',
    utente_offerta_lav: 'utente_offerta_lav',
    utente_offerta_lav_stt: 'utente_offerta_lav_stt',
    r_cat_acc_ente: 'r_cat_acc_ente',
    r_spazio_wemi_ente: 'r_spazio_wemi_ente',
    minimo_contrattuale_tcb: 'minimo_contrattuale_tcb',
    d_livello_contrattuale: 'd_livello_contrattuale',
    val_attributo_domanda: 'val_attributo_domanda',
    val_attributo_rel_dom_serv_lav: 'val_attributo_rel_dom_serv_lav',
    val_attributo_beneficiario: 'val_attributo_beneficiario',
    val_attributo_ut: 'val_attributo_ut',
    val_attributo_offerta_servizio: 'val_attributo_offerta_servizio',
    val_attributo_offerta_ut: 'val_attributo_offerta_ut',
    val_attributo_rel_off_serv_lav: 'val_attributo_rel_off_serv_lav',
    voucher: 'voucher',
    utente_offerta_servizio: 'utente_offerta_servizio',
    val_attributo_cal_off_serv_lav: 'val_attributo_cal_off_serv_lav',
    allegato_ente: 'allegato_ente',
    allegato_richiesta: 'allegato_richiesta'
}
