/**
 * The name of the template TEMPLATE_ENTE_WITH_BUTTON
 */

export const TEMPLATE_ENTE_WITHOUT_BUTTON = 'TEMPLATE_ENTE_WITHOUT_BUTTON';

/**
 * The name of the template TEMPLATE_CITTADINO
 */

export const TEMPLATE_CITTADINO = 'TEMPLATE_CITTADINO';


/**
 * The name of the template TEMPLATE_STAFF_WEMI_WITH_BUTTON
 */

export const TEMPLATE_STAFF_WEMI_WITH_BUTTON = 'TEMPLATE_STAFF_WEMI_WITH_BUTTON';

/**
 * The name of the template TEMPLATE_STAFF_WEMI_WITH_BUTTON_WITHOUT_CONTATTI
 */

export const TEMPLATE_STAFF_WEMI_WITH_BUTTON_WITHOUT_CONTATTI = 'TEMPLATE_STAFF_WEMI_WITH_BUTTON_WITHOUT_CONTATTI';

/**
 * The name of the template TEMPLATE_STAFF_WEMI_WITHOUT_BUTTON
 */

export const TEMPLATE_STAFF_WEMI_WITHOUT_BUTTON = 'TEMPLATE_STAFF_WEMI_WITHOUT_BUTTON';

/**
 * The name of the template TEMPLATE_STAFF_WEMI_WITHOUT_BUTTON_WITHOUT_CONDIZIONI
 */

export const TEMPLATE_STAFF_WEMI_WITHOUT_BUTTON_WITHOUT_CONDIZIONI = 'TEMPLATE_STAFF_WEMI_WITHOUT_BUTTON_WITHOUT_CONDIZIONI';

/**
 * The name of the template TEMPLATE_ENTE_WITH_BUTTON
 */

export const TEMPLATE_ENTE_WITH_BUTTON = 'TEMPLATE_ENTE_WITH_BUTTON';

// /**
//  * The name of the template TEMPLATE_INOLTRA_RICHIESTA_BODY
//  */

// export const TEMPLATE_INOLTRA_RICHIESTA_BODY = 'TEMPLATE_INOLTRA_RICHIESTA_BODY';

// /**
//  * The name of the template TEMPLATE_ANN_RIC_ENTE_BODY
//  */

// export const TEMPLATE_ANN_RIC_ENTE_BODY = 'TEMPLATE_ANN_RIC_ENTE_BODY';

// /**
//  * The name of the template TEMPLATE_ANN_RIC_ENTE_ADMIN_BODY
//  */

// export const TEMPLATE_ANN_RIC_ENTE_ADMIN_BODY = 'TEMPLATE_ANN_RIC_ENTE_ADMIN_BODY';


// /**
//  * The name of the template TEMPLATE_ACC_RIC_ENTE_BODY
//  */

// export const TEMPLATE_ACC_RIC_ENTE_BODY = 'TEMPLATE_ACC_RIC_ENTE_BODY';


// /**
//  * The name of the template TEMPLATE_CHAT_RIC_ENTE_BODY
//  */

// export const TEMPLATE_CHAT_RIC_ENTE_BODY = 'TEMPLATE_CHAT_RIC_ENTE_BODY';

// /**
//  * The name of the template TEMPLATE_FEEDBACK_RIC_ENTE_BODY
//  */

// export const TEMPLATE_FEEDBACK_RIC_ENTE_BODY = 'TEMPLATE_FEEDBACK_RIC_ENTE_BODY';

