export const ALLEGATO_ENTE = {
  CONDIZIONI_UTILIZZO: 'CONDIZIONI_UTILIZZO',
  PRIVACY_POLICY: 'PRIVACY_POLICY',
  MODULO_RECESSO: 'MODULO_RECESSO',
  BILANCIO_SOCIALE: 'BILANCIO_SOCIALE',
  CERTIFICAZIONI: 'CERTIFICAZIONI',
};